Feature/zk proof flow
rarimo/js-sdk pull request #54
Opened 2023-06-30 09:18 UTC by lukachi

2023-06-30 10:43 UTC, napalmpapalam requested changes

2023-06-30 10:43 UTC, napalmpapalam commented on packages/auth-zkp-iden3/src/auth-zkp.ts
> +      .post<VerifiableCredentials<T>>('', {
why u don't use as generic `VerifiableCredentials<T>` here?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/auth-zkp-iden3/src/types/auth-zkp-types.ts
> +        // serialNumber: number
/

2023-06-30 10:43 UTC, napalmpapalam commented on packages/auth-zkp-iden3/src/types/auth-zkp-types.ts
> +export type AuthZkpConfig = {
just `Config`

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/README.md
> +These packages aim to provide developers with a set of commonly used functions and features for building web applications, such as handling big numbers, date manipulation, subscribing to and receivin
/

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/README.md
> +```
move this to the main readme

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/helpers/identity-helpers.ts
> +export const initPrivateKey = (hexString?: string): string => {
`parsePrivateKey`

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/helpers/identity-helpers.ts
> +    window.crypto.getRandomValues(arr)
```ts
const generatePrivateKey = () => {
  const privateKey = new Uint8Array(32)

   if (!(typeof window === 'undefined')) {
     return window.crypto.getRandomValues(arr)
   }

   const webcrypto = require('crypto').webcrypto;
   return webcrypto.getRandomValues(privateKey);
}

export const getPrivateKey = (hexString?: string): string => {
  if (hexString) {
    return new PrivateKey(Hex.decodeString(hexString)).hex()
  }

    const privateKey = generatePrivateKey()
    return initPrivateKey(new PrivateKey(privateKey).hex())
}
```

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/identity.ts
> +  coreAuthClaim: Claim = {} as Claim
private?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/identity.ts
> +  public get identityIdBigIntString() {
```ts
 public get idString() {
    return this.identityId.string()
  }

  public get idBigIntString() {
```

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/identity.ts
> +  async createIdentity() {
create method should return something

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/identity.ts
> +    // authClaimIncProof.proof.siblings = authClaimIncProofSiblings
/

2023-06-30 10:43 UTC, napalmpapalam commented on packages/identity-gen-iden3/src/identity.ts
> +  createCoreAuthClaim() {
return type

2023-06-30 10:43 UTC, napalmpapalam commented on packages/shared/src/api/api.ts
> +export const createApi = (baseUrl: string): JsonApiClient => {
where do u use this

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/README.md
> +These packages aim to provide developers with a set of commonly used functions and features for building web applications, such as handling big numbers, date manipulation, subscribing to and receivin
\

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/README.md
> +      verifiableCredentials as VerifiableCredentials<QueryVariableName>,
why use as here

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/enums/operators.ts
> +}
pascal case

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/helpers/binary-helpers.ts
> +  const wantLen = 2 * Constants.ELEM_BYTES_LENGTH * Constants.BYTES_LENGTH
requiredLength

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/helpers/binary-helpers.ts
> +      data.slice(i * Constants.BYTES_LENGTH, (i + 1) * Constants.BYTES_LENGTH),
extract

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/helpers/binary-helpers.ts
> +    ...index.map(el => el.toBigInt().toString()),
extract map cb

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/helpers/file-helpers.ts
> +export async function readBytesFile(path: string) {
why its duplicated?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/types/contracts/common.ts
> +/* Autogenerated file. Do not edit manually. */
duplicated?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/types/contracts/factories/index.ts
> +export { StateV2__factory } from "./StateV2__factory";
duplicated?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/zkp-gen.ts
> +  subjectProof: ZKProof = {} as ZKProof
private?

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/helpers/state-v2-helpers.ts
> +export const getGISTProof = async ({
duplicated

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/zkp-gen.ts
> +import omit from 'lodash/omit'
u dont need lodash just for case where u omit 1 field

2023-06-30 10:43 UTC, napalmpapalam commented on packages/zkp-gen-iden3/src/zkp-gen.ts
> +    const { data } = await fetcher.get<Schema>(
update `@distributedlab` packages version in each package

2023-07-03 14:26 UTC, lukachi commented on packages/auth-zkp-iden3/README.md
> +```
no(

2023-07-04 16:03 UTC, napalmpapalam approved these changes

2023-07-04 16:03 UTC, merged